# WARNING - Generated by {fusen} from dev/flat_fonction_metiers.Rmd: do not edit by hand

test_that("Int works", {
  expect_equal(object = typeof(Int(3.5)),
             expected = "integer")
  expect_equal(object = typeof(Int(4)),
             expected = "integer")  
})
