# WARNING - Generated by {fusen} from dev/flat_fonction_metiers.Rmd: do not edit by hand

names <- scinde(data)
quanti <- scinde(data,"quanti")
quali <- scinde(data,"quali")
binaire <- scinde(data,"binaire")

test_that("scinde works", {
  expect_equal(object = typeof(names),
               expected = "list")
  for(i in 1:ncol(quanti))
    expect_equal(object = is.numeric(scinde(data,"quanti")[,i]),
               expected = TRUE)
  for(i in 1:ncol(quali))
  expect_equal(object = is.character(scinde(data,"quali")[,i]),
               expected = TRUE)
  for(i in 1:ncol(binaire))
    expect_equal(object = length(levels(as.factor(scinde(data,"binaire")[,i]))),
               expected = 2)
  
  

})
