# WARNING - Generated by {fusen} from dev/flat_fonction_metiers.Rmd: do not edit by hand

#' barsTriees
#' une fonction retournant  un barplot triee ggplot.
#' @param data un dataframe
#' @param var une variable qualitative
#' @import ggplot2
#' @import magrittr
#' @import dplyr
#' @import forcats
#' @return un barplot ggplot triee
#' @export
#' @examples
#' barsTriees(data,peak_name)

barsTriees <- function(data, var) {
  data |>
    mutate({{ var }} := fct_rev(fct_infreq({{ var }})))  |>
    ggplot(aes(x = {{ var }},fill= {{var}})) +
    geom_bar() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
}
