# WARNING - Generated by {fusen} from dev/flat_fonction_metiers.Rmd: do not edit by hand

#' Transforme un reel en entier
#' @param x un réel
#' @return un entier 
#' @export
#' @examples
#' Int(11)
#' Int(3.2)
Int <- function(x){
  as.integer(x)
}
